name: Branch Cron

on:
  push:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'

jobs:
  test-dispatch:
    name: Start test jobs for supported branches
    runs-on: windows-latest

    steps:
      - name: Send dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ github.token }}
          event-type: phpunit-cron
